# fly.toml file generated for mongo-gsuite-backup-staging on 2021-05-13T07:45:16+08:00

app = ""

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  allowed_public_ports = []
  auto_rollback = true